name: Test Release
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: Alexz1008/hello-world-docker-action@v1
        with:
          who-to-greet: '@octocat'
