# This is a basic workflow to help you get started with Actions

name: Reusable Workflow

# Controls when the workflow will runon:
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current-time: 
        description: 'The time when greeting'
        value: ${{ steps.time.outputs.time }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
          
